# training:
epochs: 2000
batch_size: 16
learning_rate: 0.0005 #1e-4
weight_decay: 0.00001
# data:
dataset: network_traffic
seq_len: 48
# transform:
use_stft: true
delay: 20
embedding: 16
# model:l
img_resolution: 16
input_channels: 1
unet_channels: 128
ch_mult: [1,2,4,6]
attn_resolution: [8,4,2]
diffusion_steps: 18
ema: true
ema_warmup: 50
# logging:
logging_iter: 100
num_workers: 0